### ISSUE TITLE
시간복잡도와 공간복잡도를 고려합시다.

### ISSUE THREAD

**Issue by jobumjin** [Kim-JungHwan/algorithm-study-together#50]
https://madplay.github.io/post/time-complexity-space-complexity

결국.. 자료구조를 잘 사용할 줄 알아야한다.. 공부를 해야합니다...

**Comment by jobumjin** [comment]
각 언어의 자료구조 라이브러리를 알아보는것도 좋을 것 같다.
각자 자신있는 언어의 자료구조 라이브러리를 하나씩은 찾아서 이슈댓글달아봐요!

**Comment by jobumjin** [comment]
ex : Python 
https://velog.io/@gndan4/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B4%80%EB%A0%A8-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%A3%BC%EC%9A%94-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC

**Comment by Kim-JungHwan** [comment]
Kotlin
[(https://devlog-wjdrbs96.tistory.com/395)]

**Comment by JiHyeong-Hong** [comment]
C++: https://www.joinc.co.kr/w/Site/C++/STL/About_STL#AEN46

**Comment by leorb159** [comment]
https://blog.naver.com/PostView.naver?blogId=ppuagirls&logNo=221560996691
https://kimchanjung.github.io/etc/2020/01/15/java-collection/
List : ArrayList, LinkedList
Queue : PriorityQueue, LinkedList, ArrayDequeue, DelayQueue
Set : HashSet, TreeSet, LinkedHashSet, EnumSet
Map : HashMap, TreeMap, LinkedHashMap, WeakHashMap, EnumMap

**Comment by soobaaaam** [comment]
스위프트도 자료구조 라이브러리가 없음.
아이 신나~
